PR10
IDPbIH/CSSSR-School-Junior-React pull request #10
Opened 2022-02-16 17:04 UTC by IDPbIH

2022-02-17 07:43 UTC, vislogurov requested changes

2022-02-17 07:43 UTC, vislogurov commented on src/components/Basket/Basket.jsx
> +                    <button className={s.to_basket_button} >Перейти в корзину</button>
А что делает эта кнопка, если на неё ни одного хэндлера не навесили?)

2022-02-17 07:43 UTC, vislogurov commented on src/App.js
> +                            <Route path='/404' ><NotFound /></Route>
`http://localhost:3000/productlist/%D1%86%D1%83%D0%B0%D1%8B%D0%B2%D1%81%D1%8B%D0%B2%D0%BC%D1%8B%D0%BC` вот по такому урлу возвращает главная страница

2022-02-17 07:43 UTC, vislogurov commented on src/components/AddRemoveButton/AddRemoveButton.jsx
> +                className={loading ? s.addRemove_button + ' ' + s.lock : s.addRemove_button}
Для нетривильной работы с css-правилами можно юзать https://github.com/JedWatson/classnames
Утилита позволяет в более удобном виде задавать css-классы
```
var classNames = require('classnames');

class Button extends React.Component {
  // ...
  render () {
    var btnClass = classNames({
      btn: true,
      'btn-pressed': this.state.isPressed,
      'btn-over': !this.state.isPressed && this.state.isHovered
    });
    return <button className={btnClass}>{this.props.label}</button>;
  }
}
```

2022-02-17 07:43 UTC, vislogurov commented on src/store/basketReducer.js
> +                throw new Error('Проблемы с сетью.');
Почему в этом случае нет setError? Ползователя же нужно как то уведомить о проблеме

2022-02-17 07:43 UTC, vislogurov commented on src/components/Basket/Basket.jsx
> +                    {save ? 'Очистить корзину' : 'Сохранить корзину'}
Если в корзине 0 элементов, то её можно сохранить. Выглядит странно. Предлагаю не рендерить кнопку, пока хотя бы один товар не появится в корзине

2022-02-18 05:55 UTC, IDPbIH commented on src/components/Basket/Basket.jsx
> +                    <button className={s.to_basket_button} >Перейти в корзину</button>
Ждёт своего часа) В макете Task-10-4 она есть. Я добавил

2022-02-18 05:56 UTC, IDPbIH commented on src/components/AddRemoveButton/AddRemoveButton.jsx
> +                className={loading ? s.addRemove_button + ' ' + s.lock : s.addRemove_button}
Я их юзал, на самом деле, в ProductItem. Если надо, я переделаю, но пока я не понял чем они удобнее...

2022-02-21 05:52 UTC, vislogurov commented on src/components/AddRemoveButton/AddRemoveButton.jsx
> +                className={loading ? s.addRemove_button + ' ' + s.lock : s.addRemove_button}
http://s.csssr.ru/U0FMPH83W/20200301103856_.png
Как бы такая простыня стилей выглядела без cx?)

2022-02-21 05:53 UTC, vislogurov commented on src/components/AddRemoveButton/AddRemoveButton.jsx
> +                className={loading ? s.addRemove_button + ' ' + s.lock : s.addRemove_button}
Можешь оставить, как есть, но на карандаш возьми.

2022-02-21 05:54 UTC, vislogurov approved these changes

2022-02-21 09:01 UTC, merged

2022-02-21 09:02 UTC, IDPbIH commented on src/components/AddRemoveButton/AddRemoveButton.jsx
> +                className={loading ? s.addRemove_button + ' ' + s.lock : s.addRemove_button}
Ок