PR02
IDPbIH/CSSSR-School-Junior-React pull request #2
Opened 2021-12-10 22:30 UTC by IDPbIH

2021-12-11 14:49 UTC, kuflash requested changes
Есть несколько замечаний, которые необходимо поправить

2021-12-11 14:49 UTC, kuflash commented on src/components/ProductsMainUL/ProductsMainUL.jsx
> +}
Возможно из-за задания было не совсем понятно, но тут есть недочет. Необходимо было в этом месте, внутри `li` отрисовать компонент карточки продукта и прокинуть в неё данные из JSON. Соответственно в JSON можно прописать все необходимые тебе данные, которых сейчас не хватает для отрисовки карточки.

Также, в этом месте есть не очень хороший способ отрисовки первых трех элементов. В твоем случае, если в списке из JSON будет 1000 элементов, то в map будет произведено 1000 итераций, хотя нам однозначно надо отрисовать только 3 первых элмента.

Посмотри на [методы](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array), которые есть в JS для работы с масивами и выбери подходящий, чтобы из первоначального массива данных получить только 3 элемента, а уже потом отрисовать по ним нужный тебе компонент.

2021-12-11 14:49 UTC, kuflash commented on src/components/ProductsMainH1/ProductsMainH1.jsx
> +const ProductsMainH1 = props => {
Обычно в имени компонента не указывают имя тега, так как в будущем этот тег может изменится. 
Но это не критично, и можно оставить так. Просто информация на будущее.

2021-12-11 14:49 UTC, kuflash commented on src/components/ProductsMainTable/ProductsMainTable.module.css
> +}
По макету у нас должны отображаться звезды. Из приложенного макета можно экспортировать необходимые иконки в SVG и отрисовать именно их.

Если не получится разобраться с экспортом, то пиши здесь, я помогу разобраться.

2021-12-12 17:06 UTC, kuflash commented on src/components/ProductMainTable/ProductMainTable.jsx
> +
Сейчас у нас в проекте 2 одинаковых компонента - `ProductsMainTable` и `ProductMainLIst`. Нужно оставить только один из них. Причем не забывай, по заданию нам надо выводить только 3 элемента.

2021-12-12 17:27 UTC, kuflash commented
@IDPbIH проект перестал запускаться. Перепроверь всю работоспособность проекта пожалуйста

2021-12-12 18:15 UTC, IDPbIH commented
> @IDPbIH проект перестал запускаться. Перепроверь всю работоспособность проекта пожалуйста

У меня вроде работает, поправил скобки, может, поможет...

2021-12-12 19:32 UTC, kuflash commented
> У меня вроде работает, поправил скобки, может, поможет...

@IDPbIH у тебя есть проблемы в путях к нескольким файлам. Если ты работаешь под `Windows`, то у тебя действительно может быть все ок, так как там пути до файлов не учитывают регистр символов. Но в unix-системах это важно.

Ошибка у меня такая:
<img width="690" alt="изображение" src="https://user-images.githubusercontent.com/815876/145726697-4310037c-7b99-4f16-b1ee-6689d57b7bec.png">

Проблема тут
<img width="640" alt="изображение" src="https://user-images.githubusercontent.com/815876/145726710-dfa8eed0-57cf-4d05-b6a4-68d40c4028b7.png">

И тут
<img width="680" alt="изображение" src="https://user-images.githubusercontent.com/815876/145726721-ef7b46ca-52fd-4d1f-98be-4c9c3fb67617.png">

2021-12-12 19:47 UTC, IDPbIH commented
Исправил, перезалил. Что странно, я нашел ранее эту опечатку и исправил, но почему-то вернулось...

2021-12-12 19:52 UTC, kuflash commented
@IDPbIH вот теперь все отлично :) Можешь вливать в `master`

2021-12-12 19:54 UTC, IDPbIH commented
Спасибо!)

2021-12-12 19:54 UTC, merged