PR04
IDPbIH/CSSSR-School-Junior-React pull request #4
Opened 2021-12-20 19:51 UTC by IDPbIH

2021-12-20 19:53 UTC, IDPbIH commented
Что-то совсем не получается сделать мемоизацию для filter...

2021-12-21 07:20 UTC, vislogurov requested changes

2021-12-21 07:20 UTC, vislogurov commented on src/components/FilterPage/FilterPage.jsx
> +const memoize = (fn) => {
Вынеси мемоизацию отдельно в папку `utils`, функция универсальная и может пригодиться где-то ещё

2021-12-21 07:20 UTC, vislogurov commented on src/components/FilterPage/FilterPage.jsx
> +class FilterList extends React.PureComponent {
А есть какой то профит от использования тут PureComponent?

2021-12-21 07:20 UTC, vislogurov commented on src/components/FilterPage/FilterPage.jsx
> +        (min,max,h) => <InputNumber
Что такое h?

2021-12-21 07:20 UTC, vislogurov commented on src/components/FilterPage/FilterPage.jsx
> +        (d,h) => <InputDiscount
Что такое d и h? У параметров функции должны быть "говорящие" имена.

2021-12-21 07:20 UTC, vislogurov commented on src/components/InputNumber/InputNumber.jsx
> +                    от
https://developer.mozilla.org/ru/docs/Web/HTML/Element/label забыл

2021-12-21 07:20 UTC, vislogurov commented on src/components/ProductItemWithLogRender/ProductItemWithLogRender.jsx
> +class ProductItemWithLogRender extends LogRender {
Кажется лишним создавать целый класс, чтобы просто логгер к нему прицепить.

2021-12-21 07:20 UTC, vislogurov commented on src/components/ProductItemWithLogRender/ProductItemWithLogRender.jsx
> +export default withLogRender(ProductItemWithLogRender);
Я не очень пойму — выше ты экстендишь класс от логгера, а тут ещё раз оборачиваешь в хок с логгером.  Зачем?

2021-12-21 07:20 UTC, vislogurov commented on src/components/ProductPage/ProductPage.jsx
> +class ProductPage extends React.PureComponent {
Есть какой то профит от использования тут PureComponent?

2021-12-21 07:20 UTC, vislogurov commented on src/containers/LogRender/LogRender.jsx
>  import React from 'react';
Почему `containers`?  Тут же никакой бизнес-логики нет, `shouldComponentUpdate` абсолютно служебный метод

2021-12-21 07:20 UTC, vislogurov commented on src/index.js
> +const memoize = (fn) => {
У тебя уже выше есть эта же функция мемоизации.

2021-12-21 07:20 UTC, vislogurov commented on src/index.js
> +            case 'minValueInput':
Если присмотреться, то каждый case у тебя имеет одинаковую сигнатуру изменения стейта. 
Весь метод можно сократить до `this.setState({ [e.target.name]: Number(e.target.value) });`

2021-12-21 07:20 UTC, vislogurov commented on src/index.js
> +                console.log('input error');
Чтобы узнать об ошибке, пользователю придётся смотреть в консоль. А это знание не всем доступно) Более подходящим вариантов было бы через UI показать, что инпут невалидный — добавить красную обводку или заюзать https://developer.mozilla.org/ru/docs/Web/CSS/:invalid

2021-12-21 07:20 UTC, vislogurov commented on src/index.js
> +    renderProductMainHeader = memoize(() => <ProductListHeader />)
А есть смысл тут использовать мемоизацию? Ты де никаких аргументов не передаёшь. Вот тут кажется PureComponent зайдёт

2021-12-21 08:12 UTC, IDPbIH commented on src/components/FilterPage/FilterPage.jsx
> +class FilterList extends React.PureComponent {
нет, перемудрил

2021-12-21 08:17 UTC, IDPbIH commented on src/components/ProductItemWithLogRender/ProductItemWithLogRender.jsx
> +class ProductItemWithLogRender extends LogRender {
согласен, но не пойму, как лучше "обернуть компонент карточки"

2021-12-21 08:17 UTC, IDPbIH commented on src/components/ProductItemWithLogRender/ProductItemWithLogRender.jsx
> +export default withLogRender(ProductItemWithLogRender);
перемудрил)

2021-12-21 08:20 UTC, IDPbIH commented on src/components/ProductPage/ProductPage.jsx
> +class ProductPage extends React.PureComponent {
Нет. Сейчас работает хорошо без обертки, в какой-то момент не работала мемоизация, пока не обернул в PureComponent. Странно

2021-12-21 08:26 UTC, vislogurov commented on src/components/ProductItemWithLogRender/ProductItemWithLogRender.jsx
> +class ProductItemWithLogRender extends LogRender {
А нет смысла следить за рендерами таких мелких компонентов, их дешевле перендерить, чем запускать sCU. И все компоненты нет смысла мемоизировать — в таком случае приложение будет работать медленее, чем аналогичное без мемоизации. Мемоизировать нужно там, где есть динамика изменений — списки, фильтрации итд. Эти процессы будет запускаться чаще, чем тот же самый рендер хедера, который один раз отрендерился и всё.

2021-12-21 08:39 UTC, IDPbIH commented on src/index.js
> +    renderProductMainHeader = memoize(() => <ProductListHeader />)
По 3-ему заданию было "Реализуй компонент logRender... Используй этот компонент в качестве базового для всех остальных компонентов". Он логировался при каждом рендере. Если сделать PureComponent, то отлично зайдет

2021-12-21 08:55 UTC, IDPbIH commented on src/components/ProductItemWithLogRender/ProductItemWithLogRender.jsx
> +class ProductItemWithLogRender extends LogRender {
Согласен. Но тогда я не очень понял суть задания 4.6 "Также необходимо обернуть компонент карточки товара(который импортирован из пакета) в logRenderComponent если это еще не сделано." Обернуть весь список, который выводится?

2021-12-21 08:59 UTC, vislogurov commented on src/components/ProductItemWithLogRender/ProductItemWithLogRender.jsx
> +class ProductItemWithLogRender extends LogRender {
Мысль такая — ты оборачиваешь компонент карточки -> видишь, что она рендерится в определённых случаях вхолостую -> начинаешь копать и пытаться оптимизировать. Но оптимизации эти выгоднее сделать "выше" по дереву.

2021-12-21 14:22 UTC, vislogurov commented on src/components/FilterPage/FilterPage.jsx
> +class FilterPage extends withLogRender {
Почему withLogRender лежит в папке с HOC’ами и имеет вид `with…` хотя по реализации это просто класс, который не несёт функциональности HOC.

HOC ождидает, что в него будут что-то передавать. Логика, которая подходит под вынос в HOC в этом задании, это работа с маской инпутов.

2021-12-21 14:24 UTC, vislogurov requested changes

2021-12-21 14:24 UTC, vislogurov commented on src/hoc/withSubscription .js
> +            this.props.handleSubmit(e);
`click` и `submit` это разные события.

2021-12-21 15:43 UTC, IDPbIH commented on src/hoc/withSubscription .js
> +            this.props.handleSubmit(e);
Как лучше назвать метод для двух разных событий, который обновляет общий state?

2021-12-22 07:08 UTC, vislogurov commented on src/hoc/withSubscription .js
>              e.preventDefault();;
Всегда вызывай preventDefault первым. Вот такая запись, как сейчас, например, не сработала при сабмите формы — пока вызывались бы колбэки ужк произошел бы сабмит и событие незапревентилось бы.

2021-12-22 07:08 UTC, vislogurov approved these changes

2021-12-22 18:29 UTC, IDPbIH commented on src/hoc/withSubscription .js
>              e.preventDefault();;
Ок, спасибо

2021-12-22 18:30 UTC, merged