PR05
IDPbIH/CSSSR-School-Junior-React pull request #5
Opened 2021-12-24 10:32 UTC by IDPbIH

2021-12-27 08:42 UTC, vislogurov requested changes

2021-12-27 08:42 UTC, vislogurov commented on src/components/InputCategory/InputCategory.jsx
> +                                            id={category.category}
Что будет, если тебе две и более категории понадобится выбрать? С radio так не прокатит, нужен checkbox)

2021-12-27 08:42 UTC, vislogurov commented on src/index.js
> +                product.category === category
Что будет, если выбрано несколько категорий одновременно?

2021-12-27 08:42 UTC, vislogurov commented on src/components/InputCategory/InputCategory.jsx
> +        this.categories = [
Почему категории формируются не на корневом уровне в App? Добаляя такую логику на уровне UI-компонентов ты закрываешь путь для их переиспользования. Понадобятся такие кнопки где то ещё и придётся всё копипастить.

2021-12-29 08:30 UTC, vislogurov requested changes

2021-12-29 08:30 UTC, vislogurov commented on src/components/FilterList/FilterList.jsx
> +    yo = () => {
Почему у метода такое название? Что он делает?

2021-12-29 08:30 UTC, vislogurov commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
1) Если выбраны две категории, то список не выводится вообще. При этом и категорий в урле нет
http://s.csssr.ru/U0FMPH83W/20211229112327_.png
2) Кнопка сбросить фильтры должна вообще очищать урл от всех значения. Вместо этого она заполняет урл вообще всеми данными `http://localhost:3000/p0=products&p1=cosmetics?minPriceValue=110&maxPriceValue=2000&discountValue=0&products=on&cosmetics=on`
3) http://s.csssr.ru/U0FMPH83W/20211229112555.mp4
Клик по инпуту вообще убирает весь список, приложение не реагирует на кнопки "Вперёд/Назад" (очевидно упущена часть про работу с событием popstate из урока)

2021-12-29 08:50 UTC, IDPbIH commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
1. Я делал активные категории белом цветом. Если выбраны обе категории, то выводятся все товары активных категорий
2. По заданию 2 надо сбросить фильтры. Фильтры сбрасываются. Если надо очищать URL, то пишите в задании, что надо очищать URL.
3.  Клик по input убирает весь список, потому что в state становится максимальное значение 0 и фильтр показывает значения от минимума до 0, а их нет. Но, в целом, да. Я думал, что popState для ознакомления, т.к. в задании не было указано использовать popState. Нужно использовать popState?

2021-12-29 08:53 UTC, IDPbIH commented on src/components/FilterList/FilterList.jsx
> +    yo = () => {
Ничего. Забыл удалить

2021-12-29 08:55 UTC, vislogurov commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
1. Ничего не понял, я как пользователь выбрал обе категории, а получил пустую страницу. Это приемлемый UX?)
2. Почему урл имеет такой вид после сброса `http://localhost:3000/p0=products&p1=cosmetics?minPriceValue=110&maxPriceValue=2000&discountValue=0&products=on&cosmetics=on`? По заданию нужно только категории из него читать, а не всё на свете.
3. Да, нужно использовать popstate, без этого не заработает навигация.

2021-12-29 09:10 UTC, IDPbIH commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
1. При загрузке по умолчанию активны все категории, отображаются все товары. url имеет вид http://localhost:3000/p0=cosmetics&p1=products, т.е. выбраны 2 категории(ВСЕ). Если нажать на категорию, то она перестаёт быть активной(становится синей), отображаются товары оставшихся категорий, http://localhost:3000/p0=cosmetics(к примеру).
Если убрать активные категории, то остаётся знак амперсанда и будет пусто - нет активных категорий, нет товаров. Если дело в цвете, то я могу поменять местами цвета. Если дело в логике, то я могу по умолчанию не делать категории активными вообще, не отображать товары соответственно. Но странно встречать пользователя с пустым листом на старте.
2. Ок
3. Понял

2021-12-29 09:21 UTC, vislogurov commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
1. При загрузке ты должен показывать вообще весь список, а потом уже пользователь будет фильтровать его нажимая на категории. Странно, если ты откроешь интернет-магазин, а у него по дефолту вообще все фильтры будут включены. Это не про реакт, а про хороший UX. И да, с точки зрения хорошего UX активная категория тёмная. Посмотри на макет https://www.figma.com/file/oLtxBc5f9IvNATAlQrQQ6n/5.-Context?node-id=0%3A1

2021-12-29 10:18 UTC, IDPbIH commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
По мне, странно, что показывается всё, а не выбрано ничего. Хотя я не знаю UX.  Ок, понял, сделаю, как ты говоришь.

2021-12-29 10:23 UTC, vislogurov commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
https://www.mvideo.ru/melkaya-kuhonnaya-tehnika-3/grili-198 сколько фильтров включено? Ни одного. По умолчанию показываются все товары, а уже дальше пользователь сам их фильтрует.

2021-12-29 10:44 UTC, IDPbIH commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
Судя по url https://www.mvideo.ru/melkaya-kuhonnaya-tehnika-3/grili-198, включен фильтр категории "мелкой кухонной техники" и подкатегории "грили", как мы и делали в задании "если пользователь сделал фильтрацию по категории, а потом решил послать свою ссылку другу — настройка должна сохраниться"
А на главной mvideo общая информация и реклама.
Я не хочу спорить с тем человеком, который меня учит, это ещё страннее. Просто объясняю чем я руководствовался... Ты - учитель, ты - босс!) Как скажешь, так и будет. Логику я понял.

2021-12-29 10:53 UTC, vislogurov commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
Ну ты понимаешь, что если все категории активны разом и этих категорий штук 15, а тебе нужна фильтрация только по одной, то тебе придётся сидеть и тыкать 14раз по фильтрам, чтобы осталась одна активная? Это не очень удобно.

2021-12-29 10:54 UTC, IDPbIH commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
Это аргумент!

2021-12-29 10:55 UTC, IDPbIH commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
Пользуясь случаем, хотел узнать, имеет ли смысл домашку отсылать на праздниках? Или уже после?

2021-12-29 10:58 UTC, vislogurov commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
Да, давай после.

2021-12-29 11:02 UTC, IDPbIH commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
Ок. После праздников.
И последний вопрос. Я не уверен, что успею, работы много... Но завтра ещё это задание можно попробовать досдать?

2021-12-29 11:16 UTC, vislogurov commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
Можно, каких-то жёстких дедлайнов нет)

2021-12-29 11:19 UTC, IDPbIH commented on src/components/FilterList/FilterList.jsx
>  import LogRender from '../LogRender/LogRender';
Хорошо)

2022-01-10 05:42 UTC, vislogurov commented on src/hoc/withSubscription .js
> +        // handleClick = (e) => {
Или пиши коммент почему закомментил или удаляй коммент вовсе. Иначе читающему непонятно, почему часть кода закомменчена

2022-01-11 14:46 UTC, merged