PR06
IDPbIH/CSSSR-School-Junior-React pull request #6
Opened 2022-01-16 10:19 UTC by IDPbIH

2022-01-16 11:42 UTC, kuflash requested changes
В целом все хорошо, но есть несколько моментов которые стоит исправить.

2022-01-16 11:42 UTC, kuflash commented on src/store/mainReducer.js
> +                    state.categoriesSelected)
Редьюсер по своей сути явлется чистой функцией, т.е. внутри неё не должно быть каких-то сайд-эффектов. 

У тебя возвращаемое значение зависит от того, что вернет функция `getFilteredProducts`, которая внутри себя зависит от внешних данных, которые в любой момент могут измениться и повторный вызов функции редьюсера с теми же аргументами приведет к другому результату.

Логика получения списка отфильтрованных товаров больше похожа на логику селектора. В нем ты можешь получить значения всех фильтров, которые у тебя находятся в хранилище, и на основе их отфильтровать список всех товаров.

А в хранилище можно хранить вообще весь список товаров. Он у тебя никогда не будет меняться.

2022-01-16 11:42 UTC, kuflash commented on src/store/mainReducer.js
> +export const stateResetAC = () => ({ type: STATE_RESET });
Это не существенно в данном случае, просто совет. Обрати внимание на именование всех остальных твоих AC. В их именах глагол стоит на первом месте. Это более правильный способ именовать функции/методы которые делают что-то.

А в этих двух это правило нарушается. Лучше будет так: `selectCategoryAC` и `resetStateAC`.

2022-01-16 11:42 UTC, kuflash commented on src/hoc/withHistory.js
> +                }
Вот тут есть ошибка формирования query-параметров. Query-параметры передаются после знака вопроса, а сейчас они вставляются как имя страницы: `http://localhost:3000/p0=products`. Должно быть так `http://localhost:3000/?p0=products`

2022-01-16 11:42 UTC, kuflash commented on src/hoc/withHistory.js
> +export default function withHistory(InputComponent) {
Есть недочеты в архитектуре этого HOC. Вообще хоки делаются для унификации какой-то логики, чтобы легко добавлять её в разные компоненты. Но в твоей реализации есть жесткая привязка к категориям товаров, что нарушает правило унификакации.

Если хочется сделать HOC который будет добавлять в строку браузера какие-то query-параметры, то лучше передавать их в аргументы, соответствующего метода, например в виде объекта. А этот хок занимался бы сериализацией этих параметров и проставлял их в браузерную строку.

Это конечно если я правильно понял назначение этого HOC. Если не так, то поправь меня.

2022-01-16 11:42 UTC, kuflash commented on src/hoc/withHandle.js
> +                    default:
Тут такое же замечание касательно архитектуры HOC.

Если у тебя появится еще одно поле, тебе придется его сюда добавлять. Лучше иметь один пропс с функцией, которая будет вызываться на изменение значение. Можно назваять её просто `changeInputValue`, а контейнер уже решит какой AC вызвать на этот колбек

2022-01-16 11:45 UTC, kuflash commented
@IDPbIH поля ввода цены и скидки работают странно. При блюре значение почему-то сбрасывается на стандартное. А если ввести свое значение и кликнуть на поле еще раз, то оно сбросится в `0`

https://user-images.githubusercontent.com/815876/149658489-dc0b3af6-4c4e-4b37-96fd-2f2fd6b4c685.mp4

2022-01-16 11:48 UTC, kuflash commented
@IDPbIH также фильтрация странно работает при нажатии клавиши `Enter`, пока курсор находится внутри полей/чекбоксов. Все фильтры почему-то сбрасываются. Корректный и обычный сценарий UX - при нажатии `Enter` - применение/сохранение текущих значений фильтра, а не сброс их.

https://user-images.githubusercontent.com/815876/149658655-1cb3e7c0-3890-4f6b-9b02-79b712296273.mp4

2022-01-18 10:14 UTC, IDPbIH commented on src/hoc/withHistory.js
> +export default function withHistory(InputComponent) {
Изначально идея была как-то правильно пробрасывать state не из App, если возникает popstate)

2022-01-18 15:09 UTC, kuflash approved these changes
Теперь все хорошо. У меня есть только один комментарий, но я уже сейчас апрувлю PR и это задание. Перед влитием поправь это замечание и можешь вливать в `master`

2022-01-18 15:09 UTC, kuflash commented on src/components/InputCategory/InputCategory.jsx
> +    debugger
Похоже забыл удалить

2022-01-18 15:09 UTC, kuflash commented on src/hoc/withHistory.js
> +export default function withHistory(InputComponent) {
Да, ты просто немного забежал вперед и сделал свое решение, замену которому скорее всего найдешь в раделе `Роутинг`. Там будет информация о том, как наладить общение между историей браузера и Redux-хранилищем

2022-01-18 15:10 UTC, kuflash commented on src/hoc/withHistory.js
> +export default function withHistory(InputComponent) {
Да, ты просто немного забежал вперед и сделал свое решение, замену которому скорее всего найдешь в раделе `Роутинг`. Там будет информация о том, как наладить общение между историей браузера и Redux-хранилищем

2022-01-18 16:00 UTC, IDPbIH commented on src/hoc/withHistory.js
> +export default function withHistory(InputComponent) {
Ок. Будет здорово посмотреть!

2022-01-18 16:00 UTC, IDPbIH commented on src/components/InputCategory/InputCategory.jsx
> +    debugger
Ок, спасибо)

2022-01-18 16:00 UTC, merged