PR07
IDPbIH/CSSSR-School-Junior-React pull request #7
Opened 2022-01-25 19:21 UTC by IDPbIH

2022-01-26 10:50 UTC, vislogurov requested changes

2022-01-26 10:50 UTC, vislogurov commented on src/components/Paginator/Paginator.jsx
> +        if (pages.length===0) pages.push(1);
отступы у `===` сломались.
старайся не писать if в одну строку и без скобок — это тяжело читать и по факту нарущение кодстайла, линтер это не пропустит.

2022-01-26 10:50 UTC, vislogurov commented on src/components/Paginator/Paginator.jsx
> +        for (let i = 1; i <= pageCount; i++) {
Я бы предложил более декларативно создать пагинацию через map:
`[...Array(pageCount)].map((item, key) => …` тогда и массив никакой не мутируем и не надо напрягать голову над тем, что на каждой итерации for’а происходит.

2022-01-26 10:50 UTC, vislogurov commented on src/components/Paginator/Paginator.jsx
> +                            classNameButton={page === activePage
Сделай отдельный пропс `isChecked`, который внутри LinkButton будет навешивать "активный" стиль на кнопку, если в него прилетело true.

Тогда не придётся каждый раз копипастить `? styles.active_button: styles.center_button` Как это сделано сейчас в Paginator и InputCategory.

2022-01-26 10:50 UTC, vislogurov commented on src/components/Route/Route.jsx
> +        routing: state.routing // распаршенные данные о URL
Не тяни данные из стейта напрямую, создай селектор для этого. Где нибудь ещё понадобится инфа о роутинге и будешь переписывать всё. А так селектор в одном месте храниться и возможно даже будет мемоизирован. А в текущих реалиях мемоизацию пришлось бы два раза писать — легко ошибиться.

2022-01-26 10:50 UTC, vislogurov commented on src/store/mainReducer.js
> +            (index + 1) >= (pageSize * (activePage - 1) + 1)
Выноси такие условия в отдельные переменные, чтобы из названия явно следовало, для чего она нужна. Например `const isLastPage = …`

2022-01-26 10:50 UTC, vislogurov commented on src/store/routingReducer.js
> +                    activeCategories: state.queryItems.activeCategories.includes(action.name)
У тебя же есть  функция `isCategoryActive`, кажется её можно заюзать во всех случаях когда ты проверяешь категории на includes

2022-01-26 10:50 UTC, vislogurov commented on src/store/routingReducer.js
> +                    activeCategories: []
Почему в переменной initialState у тебя `activeCategories: getActiveCategoriesFromURL`, а вот тут, когда ты вновь сбрасываешь стейт в начальное положение, `activeCategories: []`?

Разные начальные стейты могут быть?

2022-01-26 10:50 UTC, vislogurov commented on src/components/Paginator/Paginator.jsx
> +                    text='Вперёд'
Давай для кнопок назад и вперёд придумаем визуальное решение, который бы подсказало, что дальше нажать нельзя — заблочим кнопку через `pointer-events: none` и сделаем её полупрозрачной.

2022-01-26 10:50 UTC, vislogurov commented on package.json
>    "scripts": {
Замечания общего характера:
`http://localhost:3000/productlist?page=3&category=cosmetics` перейди вот по такому урлу. Ты увидищь пустую страницу со съехавшей пагинацей. Если отображать нечего, то так и указывай пользователю, что "Нет товаром удовлетворяющих условиям поиска" блаблабла

http://s.csssr.ru/U0FMPH83W/20220126134858_.png
Сетка поехала

2022-01-26 10:50 UTC, vislogurov commented on src/index.js
> +                    <div className='box3'><Route path='/productlist'><ProductListContainer /></Route></div>
1. Чем `http://localhost:3000/productlist` отличается от `http://localhost:3000`
2.  Почему два разных компонента box3 и box4 ведут на один и тот же `path`?

2022-01-26 19:18 UTC, IDPbIH commented on src/components/Paginator/Paginator.jsx
> +        if (pages.length===0) pages.push(1);
Понял. Про линтер не очень...

2022-01-26 19:20 UTC, IDPbIH commented on src/index.js
> +                    <div className='box3'><Route path='/productlist'><ProductListContainer /></Route></div>
1. Наличием pathname
2. Может, я не особо разобрался в вопросе, но box3 и box4 должны были рендериться при path='/productlist'. Переделал

2022-01-27 14:34 UTC, vislogurov commented on src/components/Paginator/Paginator.jsx
> +        if (pages.length===0) pages.push(1);
Если бы в проекте был настроен линтер, он бы тебе не дал закоммитить такой код.

2022-01-27 14:37 UTC, vislogurov commented on src/index.js
> +                    <div className='box3'><Route path='/productlist'><ProductListContainer /></Route></div>
Ну сейчас они рендерятся и просто на localhost:3000))) Непонятно какую часть ТЗ ты пытался реализовать. Следующая часть будет про роутинг, так что, там ещё разберёмся с нюансами роутов.

2022-01-27 15:30 UTC, IDPbIH commented on src/index.js
> +                    <div className='box3'><Route path='/productlist'><ProductListContainer /></Route></div>
Никакую часть... Тестил пример из текста к заданию. В редьюсере настроено, чтобы работал при пустом path.
Ок.

2022-01-27 19:02 UTC, merged