PR09
IDPbIH/CSSSR-School-Junior-React pull request #9
Opened 2022-02-10 07:57 UTC by IDPbIH

2022-02-11 16:23 UTC, kuflash requested changes
Все отлично, есть только один момент.

Попробуй как-то улучшить компонент просмотра продукта. Надо либо весь компонент унифицировать, либо логику, которую я пометил как дублирующую.

2022-02-11 16:23 UTC, kuflash commented on src/components/ProductItemVertical/ProductItemVertical.jsx
> +    const maxStars = 5;
Вот эта логика дублируется в 2х компонентах, которые отличаются только способом отображения данных (вертикальное/горизонатльное).

Нет возможности сделать это все одним компонентом и менять отображение через стили? По идее flexbox тебе может помочь. У него есть возможность изменить способ отображения с `row` на `column`.

2022-02-11 17:57 UTC, IDPbIH commented on src/components/ProductItemVertical/ProductItemVertical.jsx
> +    const maxStars = 5;
По красоте!) Думал, как правильнее сделать...

2022-02-12 08:34 UTC, kuflash commented
@IDPbIH теперь все замечательно :) Можешь вливать в `master`

2022-02-12 08:54 UTC, merged